### ISSUE TITLE
are you sure this works?

### ISSUE THREAD

**Issue by pakair** [T-vK/LedStripSimulator#1]
I clicked on the online link, I cannot see the examples or add my code. What am I missing? thx

Linux Mint 19.3, Firefox 87.0

**Comment by T-vK** [comment]
It used to work. Let me check.

**Comment by T-vK** [comment]
Sorry for the inconvenience. The online demo was probably broken for quite some time now. 
This should work: https://t-vk.github.io/LedStripSimulator/

**Comment by pakair** [comment]
Thank you, the link you provided works.
